name: Crystal-Miners
version: 1.0.5
main: com.crystalminers.System.Main
author: DragonSephHD
description: CrystalMiners Serversystem
commands:
  speed:
    description: Verändert deine Geschwindigkeit
  fly:
    description: Flugmodus ein oder ausschalten
  crash:
    description: Crasher
  crystalminers:
    description: CrystalMiners Serversystem
    aliases: [cm, crystal, system]